# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10dddcab04b1d9e9bb602a3061e269b2d3837d01a6cddf6077fc0c0a508444518c6a608ee3fdcb3ec1be466a0dd16a944f9061aba2a6d9d903757eb9eb4bb4dd

test:
  secret_key_base: ba0681f7533b07c18c313bb82cb3eddc7b4d1ad679ccc3ebcbedfd41e93f19aa2a117594591b2a72c86b4c40e16aa3d36f37e9e9fe1cf3eeaa038f745c700772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
